server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: fanjialin1101
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mjj.travelling.model

